"""Changed seed data

Revision ID: 1bee77b276a4
Revises: f442d2c42cfb
Create Date: 2024-02-13 22:10:58.371735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bee77b276a4'
down_revision = 'f442d2c42cfb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
