"""Changed seed data

Revision ID: 6de27d8c7245
Revises: 5b916b76b5a6
Create Date: 2024-02-13 22:16:11.090778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6de27d8c7245'
down_revision = '5b916b76b5a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
