"""Changed seed data

Revision ID: 6de21044d0e6
Revises: e8a94699cb2a
Create Date: 2024-02-13 22:29:03.207810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6de21044d0e6'
down_revision = 'e8a94699cb2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
