"""Changed seed data

Revision ID: e8a94699cb2a
Revises: 6de27d8c7245
Create Date: 2024-02-13 22:24:12.522548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8a94699cb2a'
down_revision = '6de27d8c7245'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
