"""Updated model

Revision ID: f442d2c42cfb
Revises: c12c4ce36c08
Create Date: 2024-02-13 21:30:50.838327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f442d2c42cfb'
down_revision = 'c12c4ce36c08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'comment')
    op.drop_column('reviews', 'score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('score', sa.INTEGER(), nullable=True))
    op.add_column('reviews', sa.Column('comment', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
